plugin.plugin_configuration.search_api_backend.meilisearch:
  type: mapping
  label: 'Meilisearch backend configuration'
  mapping:
    connection_mode:
      type: string
      label: 'Connection mode (self_hosted|cloud)'
    host:
      type: string
      label: 'Host URL'
    port:
      type: integer
      label: 'Host port'
    api_key:
      type: string
      label: 'API key'
    is_cloud:
      type: boolean
      label: 'Is Meilisearch Cloud'
    search_mode:
      type: string
      label: 'Search mode (keyword|semantic|hybrid)'
    semantic_ratio:
      type: float
      label: 'Semantic ratio (0.0 - 1.0)'
    embedder:
      type: string
      label: 'Embedder name'
