name: Tests

on:
  push:
    branches: [main, 1.x]
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - drupal: '^11'
            meilisearch: 'v1.54'
          - drupal: '^10.3'
            meilisearch: 'v1.54'
    env:
      MEILISEARCH_VERSION: ${{ matrix.meilisearch }}
    steps:
      - uses: actions/checkout@v4
      - name: Build test image
        run: docker compose build --build-arg DRUPAL_CORE='${{ matrix.drupal }}' tests
      - name: Run PHPUnit
        run: scripts/test.sh
